image:
    name: jakzal/phpqa:php8.1
    pull_policy: if-not-present

cache:
    paths:
        - vendor/
        - node_modules/

stages:
    - securityChecker
    - codingStandards
    - testing
    - build
    - release

.install-composer-deps: &install-composer-deps
    - composer install --ignore-platform-reqs --no-interaction --no-progress --no-suggest --prefer-dist

security-checker:
    stage: securityChecker
    script:
        - *install-composer-deps
        - local-php-security-checker  --path=./composer.lock
    allow_failure: false
    only:
        - merge_requests

php-cs-fixer:
    stage: codingStandards
    script:
        - *install-composer-deps
        - php-cs-fixer fix src --config=.php-cs-fixer.dist.php --dry-run --diff --verbose --ansi
    allow_failure: false
    only:
        - merge_requests

phpstan:
    stage: codingStandards
    script:
        - *install-composer-deps
        - phpstan analyse ./src
    allow_failure: false
    only:
        - merge_requests

twig-lint:
    stage: codingStandards
    script:
        - *install-composer-deps
        - twig-lint lint ./templates
    allow_failure: false
    only:
        - merge_requests

phpunit:
    stage: testing
    script:
        - *install-composer-deps
        - php vendor/bin/phpunit --configuration tests/phpunit.xml --testsuite unit
    allow_failure: false

build-php:
    stage: build
    script:
        - composer install --no-dev --optimize-autoloader --ignore-platform-reqs --prefer-dist --no-scripts
    only:
        - tags
    artifacts:
        paths:
            - vendor

build-node:
    stage: build
    image:
        name: node:16
        pull_policy: if-not-present
    script:
        - yarn install
        - yarn build
    only:
        - tags
    artifacts:
        paths:
            - public/build

release:
    stage: release
    image:
        name: registry.gitlab.com/gitlab-org/release-cli:latest
        pull_policy: if-not-present
    rules:
        -   if: $CI_COMMIT_TAG
    dependencies:
        - build-php
        - build-node
    needs:
        - job: build-php
          artifacts: true
        - job: build-node
          artifacts: true
    artifacts:
        paths:
            - project.tar.gz
    script:
        - ls -la
        - tar -czf project.tar.gz .
        - |
            release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
              --assets-link "{\"name\":\"project\",\"url\":\"${CI_SERVER_URL}/${CI_PROJECT_PATH}/-/jobs/$CI_JOB_ID/artifacts/raw/project.tar.gz\"}" \
              --assets-link "{\"name\":\"project-api\",\"url\":\"${CI_SERVER_URL}/api/v4/projects/$CI_PROJECT_ID/jobs/$CI_JOB_ID/artifacts/project.tar.gz\"}"
